### ISSUE TITLE
Request for Discussion: Own Github Organization for BiSecure GW

### ISSUE THREAD

**Issue by thomasletsch** [thomasletsch/bisecure-gateway#12]
I would like to discuss if we should move this repository to a separate github organization.
I started with the openhab binding and that is another repo inside my personal repo. 

We would need some kind of cool name, but than we could move all related repos into this team.

On the long run we could also split the current SDK and APP, making it easier for others to find the right sources to work on. This task is not for now since it is probably easier to have it in one repo while developing the app.

What do you think?

**Comment by warting** [comment]
Haha, that's a no brainier. That's exactly my thoughts when I was setting
up Travis. how about the lame name "open sesame" ? It's fun because it's OPEN source and opens a gate :)

I think we should split it into seperat repo fairly soon to keep the repos small. Android tend to slow down the build system for other apps in same projects.

**Comment by thomasletsch** [comment]
Great :-). Same thoughts!

I like open sesame, it sounds funny and fitting. Unfortunately, because of that, there are already various opensesame repos in github... but I think none organization with that name.

Another idea of mine was hoerbi,  sounding like herbie (the VW beetle number 53 from the movies https://www.imdb.com/title/tt0400497/).

**Comment by warting** [comment]
The sounding would work in sweden but the spelling looks like scrambled letters and no one would know how to spell it correctly if telling someone to search for 🎶Herbie🎵 Otherwize - great movie + reference :)

**Comment by thomasletsch** [comment]
Yeah, I agree with that :-). 
How about we adjust Open Sesame slightly to make it unique but still clearly understandably that it is based upon the aladdin movie?

**Comment by warting** [comment]
Sure, any suggestion?

**Comment by thomasletsch** [comment]
Not really :-). 
Perhaps we get the searchability anyway with the right keywords in our readme.
I would like to see if we get an idea today. If not lets go with open sesame and we do not waste too much time with the naming... ok?

**Comment by warting** [comment]
sound good to me, the org-name is changable. So not written in stone

**Comment by thomasletsch** [comment]
OK, no better idea here, lets got with Open Sesame :-) !!!!!

**Comment by thomasletsch** [comment]
Ok, open sesame is already taken as github organization. Should have checked that earlier :-(.
How about 
Open Bison (sounds like Sesame with the Bi from BiSecure)
Free Herbie :-)
Open Hobig (Hobig = HOerman BIsecure Gateway)

Come on, lets brain storm :-)

**Comment by warting** [comment]
It was super hard to find a name that was not used.
How about creating an organization named "bisdk" and then whatever platform we build the app for, it will have different names. if we go with bisdk  the domain bisdk.org is available as well

**Comment by thomasletsch** [comment]
Yes, finding a free name is quite a tough call. 
bisdk sounds good for me and its free :-)

**Comment by warting** [comment]
Cool, let's do it
